[tool.poetry]
name = "sdc-scissor"
version = "2.0.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.0.4"
beamngpy = "^1.22"
pandas = "^1.4.1"
Shapely = "^1.8.1"
scikit-learn = "^1.0.2"
pymoo = "0.4.2.2"

[tool.poetry.dev-dependencies]
parameterized = "^0.8.1"
Sphinx = "^4.5.0"
sphinx-rtd-theme = "^1.0.0"
pytest = "^7.1.2"
coverage = "^6.3.2"
pytest-mock = "^3.7.0"
black = "^22.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
