[tool.poetry]
name = "sdc-scissor"
version = "0.2.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = ">=3.7.9,<3.11"
click = "^8.0.3"
PyYAML = "^5.4.1"
beamngpy = "^1.21.1"
scikit-learn = "^1.0.1"
joblib = "^1.1.0"
deap = "^1.3.1"
parameterized = "^0.8.1"
colorama = "^0.4.4"
cycler = "^0.11.0"
descartes = "^1.1.0"
fonttools = "^4.28.2"
importlib-metadata = "^4.8.2"
Jinja2 = "^3.0.3"
kiwisolver = "^1.3.2"
MarkupSafe = "^2.0.1"
matplotlib = "^3.5.0"
msgpack = "^1.0.3"
numpy = "^1.19.5"
opencv-python = "^4.5.1.48"
packaging = "^21.3"
pandas = "^1.3.5"
Pillow = "^8.4.0"
PyOpenGL = "^3.1.5"
pyparsing = "^3.0.6"
python-dateutil = "^2.8.2"
scipy = "^1.7.3"
setuptools-scm = "^6.3.2"
Shapely = "^1.8.0"
tensorflow = "^2.4.1"
tomli = "^1.2.2"
zipp = "^3.6.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
